### PR TITLE
Add size limit library to check size

### PR DESCRIPTION
**Pull request by polemius**
This PR added library to check size of library. More about this library here: https://github.com/ai/size-limit

### CODE REVIEW

**Comment by omnidan** [comment]
@polemius thanks for the PR! currently, running `size-limit` is failing on travis CI. the CLI package might be missing (I only see the preset package), can you please check?

**Comment by polemius** [comment]
This error because in travis config file node has version 4. It is old version so I changed the version to 10.

**Comment by omnidan** [comment]
@polemius thank you! everything looks good now

**Comment by polemius** [comment]
Thanks!

**Pull request merged**
